name: ml-pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Fix pathspec for DVC
        run: |
          pip uninstall -y pathspec
          pip install pathspec==0.11.2
          pip install --upgrade dvc

      - name: DVC pull
        run: dvc pull

      - name: Run tests
        run: pytest -q

  train:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Fix pathspec for DVC
        run: |
          pip uninstall -y pathspec
          pip install pathspec==0.11.2
          pip install --upgrade dvc

      - name: DVC pull
        run: dvc pull

      - name: Train model
        run: python src/heart_disease_mlops/train.py

